- requirements.txt
- xmipptomo/protocols/protocol_apply_alignment_subtomo.py
- xmipptomo/protocols/protocol_cltomo.py
- xmipptomo/protocols/protocol_connected_components.py
- xmipptomo/protocols/protocol_coords_roi.py
- xmipptomo/protocols/protocol_project_top.py
- xmipptomo/protocols/protocol_subtomo_map_back.py
- xmipptomo/protocols/protocol_undo_alignment_subtomo.py
- xmipptomo/tests/test_protocols_xmipptomo.py
Small fixes due to migration and missing tests
> migration fixes

- xmipptomo/protocols.conf
- xmipptomo/protocols/__init__.py
- xmipptomo/protocols/protocol_randomMisalignment.py
Pull request for the random misalignment of tilt-series.
This pull request includes:
- Changes in init to link the new protocol
- Changes in protocols.conf including the new protocol
- The new tilt-series misalignment protocol
> Fi feature random misalignment

- xmipptomo/protocols/protocol_randomMisalignment.py
Remove unnecessary imports from random misalignment
> remove unecesary imports

- xmipptomo/protocols/protocol_randomMisalignment.py
- Changes in  random misalignment protocol to allow new sources of noise
> Fi feature mis ali ts

- xmipptomo/protocols.conf
- xmipptomo/protocols/__init__.py
- xmipptomo/protocols/protocol_randomMisalignment.py
- Typos fixes in ts misalignment protocol
> Fi fixes miss ali ts

- xmipptomo/protocols.conf
- xmipptomo/protocols/__init__.py
- xmipptomo/protocols/protocol_splitTS.py
Pull request for a new protocol to split tilt-series into its odd-even elements.
This pull request includes:
- Changes in init to link the new protocol
- Changes in protocols.conf including the new protocol
- The new tilt-series misalignment protocol
> Fi feature split ts

- xmipptomo/__init__.py
- xmipptomo/bibtex.py
Fix citation as suggested in https://github.com/scipion-em/scipion-em-tomo/issues/66.
As the specific methods used in xmipptomo have not been published and many of them used existing methods in Xmipp3, I decided to add as citation the "most general" paper that I found about Xmipp3. 
Not sure if this PR has to go to devel or master.
> Fix citation

- xmipptomo/protocols.conf
- xmipptomo/protocols/__init__.py
- xmipptomo/protocols/protocol_flexalign.py
This requires both Xmipp and Scipion-em-Xmipp to be present. May I assume that this is true? @pconesa  @JorMaister
> adding FlexAlign for tilt series alignment

- xmipptomo/protocols/protocol_misalignTS.py
- Changes in misalignTS protocol in order to save the misalignment matrix as file
> output misalignment TM as file too

- xmipptomo/protocols.conf
- xmipptomo/protocols/__init__.py
- xmipptomo/protocols/protocol_applyAlignmentTS.py
- New protocol to apply transformation matrices to one set of tilt-series
- Changes needed in init and protocols.conf
> Fi feature apply transformation matrix to tilt-series

- xmipptomo/protocols.conf
- xmipptomo/protocols/__init__.py
- xmipptomo/protocols/protocol_resizeTS.py
- New protocol to resize tilt-series
- Needed changes in protocols.conf
- Needed changes in init
> Fi feature resize ts

- requirements.txt
- xmipptomo/protocols.conf
- xmipptomo/protocols/__init__.py
- xmipptomo/protocols/protocol_align_transform.py
- xmipptomo/protocols/protocol_score_transform.py
- xmipptomo/tests/test_protocols_xmipptomo.py
Two new protocols added:
- `protocol_align_transform` performs a rigid alignment of the transformations associated with a series of Subtomograms to a common axis
- `protocol_score_transform` gives a distance score by comparing the corresponding alignments associated with different subtomograms using quaternions
`protocol_score_transform` has a test that will remain commented until the datasets available for tomography include the appropriate data
> Transformation Matrix Scoring

- xmipptomo/protocols/protocol_splitTS.py
- Fixes in the output dimensions in split TS protocol
> Fi fixes split ts

- xmipptomo/protocols/protocol_align_transform.py
- xmipptomo/protocols/protocol_applyAlignmentTS.py
- xmipptomo/protocols/protocol_apply_alignment_subtomo.py
- xmipptomo/protocols/protocol_cltomo.py
- xmipptomo/protocols/protocol_connected_components.py
- xmipptomo/protocols/protocol_coords_roi.py
- xmipptomo/protocols/protocol_fit_ellipsoid.py
- xmipptomo/protocols/protocol_flexalign.py
- xmipptomo/protocols/protocol_misalignTS.py
- xmipptomo/protocols/protocol_phantom_subtomo.py
- xmipptomo/protocols/protocol_project_top.py
- xmipptomo/protocols/protocol_resizeTS.py
- xmipptomo/protocols/protocol_roiIJ.py
- xmipptomo/protocols/protocol_score_coordinates.py
- xmipptomo/protocols/protocol_score_transform.py
- xmipptomo/protocols/protocol_splitTS.py
- xmipptomo/protocols/protocol_subtomo_map_back.py
- xmipptomo/protocols/protocol_subtraction_subtomo.py
- xmipptomo/tests/test_protocols_xmipptomo.py
This PR should be merged once scipion-em-tomo is updated with coordinates3D modifications
> Coordinates 3D modifs + BETA labels

- xmipptomo/protocols.conf
- xmipptomo/protocols/__init__.py
- xmipptomo/protocols/protocol_rotate_astigmatism.py
- xmipptomo/utils.py
- New protocol for astigmatism rotation in CTF estimation
- New utils script for calculation methods
- Changes needed in protocols.conf
- Changes needed in init
THIS PR HAS A DEPENDENCY WITH scipion-em/scipion-em-tomo#123
> Fi feature rotate astigamtism

- xmipptomo/protocols/protocol_rotate_astigmatism.py
- Fixes in rotate astigmatism protocol.
> Fi fixes rotate astig

- xmipptomo/__init__.py
- xmipptomo/protocols/protocol_rotate_astigmatism.py
- Fixes in rotate astigmatism
- Bump version
> Fi fixes alter

- xmipptomo/protocols.conf
Please review that your protocols are in the correct section :)
> new scheme for tomo menu

- xmipptomo/protocols/protocol_rotate_astigmatism.py
- Fixes and refactor in rotate astigmatism
> Fi fixes workshop

- xmipptomo/protocols/__init__.py
- xmipptomo/protocols/protocol_phantom_subtomo.py
- xmipptomo/protocols/protocol_phantom_tomo.py
- xmipptomo/viewers/__init__.py
- xmipptomo/viewers/viewer_phantom_create.py
This adds a new tomo phantom protocol that outputs coordinates with the latest matrix convention.
If I've done it right that output could be used to verify other conventions and the coordinates viewers.
> Subtomo phantom tweaks + tomo phantom

- xmipptomo/protocols/protocol_apply_alignment_subtomo.py
- xmipptomo/protocols/protocol_phantom_tomo.py
phantom subtomo generates back particles over white background
> fix apply alignment: error each 10 of subtomos

- xmipptomo/protocols/protocol_apply_alignment_subtomo.py
- xmipptomo/protocols/protocol_phantom_tomo.py
use step methods instead of strings
phantom tomo "methods" revamped
> possible outputs defined for ApplyTransform subtomos

- xmipptomo/protocols/protocol_phantom_tomo.py
fixes the transformation test in scipion-em-tomo
tomo phantom adds noise to the tomgrams.
> Test transformations

- xmipptomo/protocols/protocol_applyAlignmentTS.py
- Fixes in applying TM to TS checking for rotations >45º and swapping dimensions.
> Fixes in apply transformation matrix to TS

- xmipptomo/protocols/protocol_phantom_subtomo.py
- xmipptomo/protocols/protocol_phantom_tomo.py
- xmipptomo/protocols/protocol_project_top.py
- xmipptomo/protocols/protocol_subtomo_map_back.py
- xmipptomo/tests/test_protocols_xmipptomo.py
subtomo phantom fixed when generating coordinates
> Mapback refactored and test fixed

- xmipptomo/protocols/protocol_misalignTS.py
Don't save TM in interpolated TS
> dont save tm in interpolated ts

- xmipptomo/protocols/protocol_splitTS.py
- xmipptomo/tests/__init__.py
- xmipptomo/tests/test_protocols_xmipptomo.py
- Fixes in split tilt series (output dimensions wrong)
- Test for split tilt series
> Fi test split ts

- CHANGES.txt
- xmipptomo/__init__.py
- xmipptomo/protocols/protocol_phantom_subtomo.py
- xmipptomo/protocols/protocol_phantom_tomo.py
- xmipptomo/protocols/protocol_score_transform.py
- xmipptomo/tests/test_protocols_xmipptomo.py
- xmipptomo/viewers/__init__.py
- xmipptomo/viewers/viewer_score_subtomos.py
score transformation refactored. Viewer added.
version bumped
> phantom subtomos: allow a fixed seed for test.

- xmipptomo/objects.py
- xmipptomo/protocols/__init__.py
- xmipptomo/protocols/protocol_denoising_confidence.py
- xmipptomo/protocols/protocol_extract_particlestacks.py
- xmipptomo/protocols/protocol_flexalign.py
- xmipptomo/utils.py
This PR depends on this one
https://github.com/I2PC/scipion-em-xmipptomo/pull/123
> Adding new method confidence map

- xmipptomo/protocols/protocol_project_subtomograms.py
- xmipptomo/tests/test_protocol_project_subtomograms.py
This protocolo now can perform parallel calls to xmipp, which makes it way faster for huge datasets (like the one being used in my Master's thesis).
> Parallelized protocol project subtomograms

- .github/workflows/buildPlugin.yml
This should fix CUDA installation failing sometimes, and making it way faster (3min instead of ~8min).
> Improved CUDA installation command

- xmipptomo/protocols/protocol_deep_misalignment_detection.py
- xmipptomo/utils.py
- Recover deleted methods in utils
- Adapt deep_misalignment_detection protocol to changes in xmipp_tomo_subtomogram_extraction parameters
> Recover deleted methods

- xmipptomo/utils.py
- Shutil was being used & not imported
- Some code smells removed
> Fix bugs & code smells

- xmipptomo/protocols/protocol_deep_misalignment_detection.py
- xmipptomo/tests/test_protocol_deep_misalignment_detection.py
This PR includes an update in the code for deep misalignment detection on tomograms after some changes in the xmipp program
IMPORTANT: This PR depends on https://github.com/I2PC/xmipp/pull/848
> Fi dmd update model

- xmipptomo/protocols/protocol_extract_subtomos.py
Improve readability of subtomogram extraction. Added toggle to select the source of the tomograms.
> improve extract subtomos readability

- .github/workflows/buildPlugin.yml
- .gitignore
- xmipptomo/protocols/protocol_cltomo.py
- xmipptomo/protocols/protocol_project_subtomograms.py
- xmipptomo/testData.json
- xmipptomo/tests/test_protocol_cltomo.py
- Also added a function to free up space in action worker's disk (in scipion-chem we ran into disk size issues, so, doing it also here does not hurt and might help avoid them in the future)
> Automatic tests inside actions

- xmipptomo/protocols/protocol_phantom_subtomo.py
- xmipptomo/protocols/protocol_phantom_tomo.py
Based on SonarCloud alerts defined [here](https://github.com/I2PC/scipion-em-xmipptomo/security/code-scanning/17), among other 16 ones.
Will wait for #179 to be merged so this can be properly tested.
> Updated deprecated function call
